### PR TITLE
Add an optimize flag to the metric specification

### PR DESCRIPTION
**Pull request by jgustie**
This PR adds an optimize field to the metric definition.

### CODE REVIEW

**Comment by jgustie** [comment]
This is still waiting on backend changes to be deployed.

**Comment by bradbeam** [comment]
Are we missing v1beta1 and the new crd definitions?

**Comment by jgustie** [comment]
That's a different [PR](https://github.com/redskyops/redskyops-controller/pull/215).

**Comment by bradbeam** [comment]
Whoops, missed this was not the controller repo.

**Review by bradbeam — APPROVED** [review]

**Pull request merged**
